

// This program was generated by Chat GPT based on my python code

#include <stdio.h>
//#include <stdlib.h>
//#include <stdint.h>
//#include <stdbool.h>
//#include <string.h>
//#include <inttypes.h>
//#include <time.h>
#include "caepher.h"



static const char b64_table[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789+/";

char* bytes_to_base64(const byte* data,
                      size_t      len)
{
    size_t enc_len = 4 * ((len + 2) / 3);
    char* enc = malloc(enc_len + 1);
    if (!enc) exit(1);

    size_t i = 0, j = 0;
    for (; i + 2 < len; i += 3) {
        uint32_t tri = (data[i] << 16)
                     | (data[i+1] << 8)
                     |  data[i+2];
        enc[j++] = b64_table[(tri >> 18) & 0x3F];
        enc[j++] = b64_table[(tri >> 12) & 0x3F];
        enc[j++] = b64_table[(tri >>  6) & 0x3F];
        enc[j++] = b64_table[ tri        & 0x3F];
    }
    if (i < len) {
        byte a = data[i];
        byte b = (i + 1 < len) ? data[i+1] : 0;
        uint32_t tri = (a << 16) | (b << 8);
        enc[j++] = b64_table[(tri >> 18) & 0x3F];
        enc[j++] = b64_table[(tri >> 12) & 0x3F];
        if (i + 1 < len) {
            enc[j++] = b64_table[(tri >> 6) & 0x3F];
        } else {
            enc[j++] = '=';
        }
        enc[j++] = '=';
    }
    enc[j] = '\0';
    return enc;
}

char* key_string(const byte* key,
                 size_t key_len)
{
    return bytes_to_base64(key, key_len);
}

// ─── Demo main ─────────────────────────────────────────────────────────────


clock_t start;

void start_clock(void) {
    start = clock();
}

void print_elapsed(const char *message) {
    clock_t end = clock();
    double cpu_sec = (double)(end - start) / CLOCKS_PER_SEC;
    printf("%s time elapsed: %.6f seconds\n", message, cpu_sec);
}

int main(void) {
    load_rules_from_csv("reversible.csv");

    start_clock();

    const char* message = "secret message";
    size_t message_len = strlen(message);

    byte* private_key = NULL;
    size_t private_key_len = 0;
    byte* public_key  = NULL;
    size_t public_key_len  = 0;

    generate_key_pair(
        _N,
        15,
        3,
        10000,
        &private_key,
        &private_key_len,
        &public_key,
        &public_key_len);

    print_elapsed("Generated keypair");

    size_t cipher_len;
    byte* cipher = encrypt(
        public_key,
        public_key_len,
        (const byte*)message,
        message_len,
        &cipher_len);

    print_elapsed("Encrypted message");

    size_t plain_len;
    byte* plain = decrypt(
        private_key,
        private_key_len,
        cipher,
        cipher_len,
        &plain_len);

    print_elapsed("Decrypted message");

    if (plain_len != message_len ||
        memcmp(plain, message, message_len) != 0)
    {
        fprintf(stderr,"Decryption failed\n");
        return 1;
    }

    printf("Original : %s\n", message);
    printf("Decrypted: %.*s\n", (int)plain_len, plain);

    char* pub_b64 = key_string(public_key, public_key_len);
    char* prv_b64 = key_string(private_key, private_key_len);

    printf("Private Key (%ld bits, base64): %s\n", private_key_len, prv_b64);
    printf("Public Key (%ld bits, base64): %s\n", public_key_len, pub_b64);

    free(private_key);
    free(public_key);
    free(cipher);
    free(plain);
    free(pub_b64);
    return 0;
}
