

// This program was generated by Chat GPT based on my python code

#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <inttypes.h>
#include <time.h>
#include <arpa/inet.h>    // htonl, ntohl, htons, ntohs

#define _N 5

// Header sizes: 16-byte identifier + fields + padding = 32 bytes
#define _MESSAGE_HEADER_SIZE  32
#define _PUBLIC_HEADER_SIZE   32
#define _PRIVATE_HEADER_SIZE  32

static const char* _ENCODING_VERSION = "CAE-0.1";

typedef uint32_t state_t;  // holds up to 15-bit CA states
typedef uint8_t  byte;


// ─── Rules ───────────────────────────────────────────────

// A table representing a full CA lookup of size 2^L bits.
typedef struct {
    size_t bits;   // = 1 << L
    size_t bytes;  // = (bits + 7) / 8
    byte*  tbl;    // bit-packed lookup table
} RuleTable;

#define MAX_CSV_L 32

typedef uint32_t state_t;

typedef struct {
    size_t count;
    state_t *values;
} RuleList;

static RuleList rule_lists[MAX_CSV_L+1];

void load_rules_from_csv(const char *filename) {
    FILE *f = fopen(filename, "r");
    if (!f) { perror("fopen"); exit(1); }
    char line[256];

    // skip header
    if (!fgets(line, sizeof(line), f)) {
        fclose(f);
        return;
    }

    while (fgets(line, sizeof(line), f)) {
        // trim newline
        char *p = strchr(line, '\n');
        if (p) *p = '\0';

        long rule;
        int L;
        if (sscanf(line, "%ld,%d", &rule, &L) == 2 &&
            L >= 0 && L <= MAX_CSV_L)
        {
            RuleList *rl = &rule_lists[L];
            rl->values = realloc(rl->values, (rl->count + 1) * sizeof(state_t));
            rl->values[rl->count++] = (state_t)rule;
        }
    }
    fclose(f);

    // seed randomness
    srand((unsigned)time(NULL));
}

void get_random_reversible_rules(int L, size_t n, state_t* out_rules) {
    if (L < 0 || L > MAX_CSV_L || rule_lists[L].count == 0) {
        fprintf(stderr, "No rules loaded for L=%d\n", L);
        exit(1);
    }
    RuleList *rl = &rule_lists[L];
    for (size_t i = 0; i < n; i++) {
        size_t idx = rand() % rl->count;
        out_rules[i] = rl->values[idx];
    }
}


// ─── Bit & rotation utilities ───────────────────────────────────────────────

static inline byte bit_at(state_t x, int k) {
    return (x >> k) & 1U;
}

state_t rotate_right(state_t state,
                     int     shift,
                     int     L)
{
    shift %= L;
    state_t low = state & ((1U << shift) - 1);
    return (state >> shift)
         | (low << (L - shift));
}

// ─── Integer ↔ bytes, Base64 ────────────────────────────────────────────────

byte* int_to_bytes(state_t i,
                   int     n_bits,
                   size_t* out_len)
{
    *out_len = (n_bits + 7) / 8;
    byte* buf = malloc(*out_len);
    if (!buf) exit(1);
    for (size_t j = 0; j < *out_len; j++) {
        buf[*out_len - 1 - j] =
            (byte)((i >> (8*j)) & 0xFF);
    }
    return buf;
}


// ─── Chunking & unchunking ─────────────────────────────────────────────────

// Exactly mirrors Python’s chunk_bytes
state_t* chunk_bytes(const byte* data,
                     size_t      data_len,
                     int         size,
                     size_t*     out_chunks_len)
{
    size_t total_bits = data_len * 8;
    *out_chunks_len = (total_bits + size - 1) / size;
    state_t* chunks =
      malloc(*out_chunks_len * sizeof(state_t));
    if (!chunks) exit(1);

    // Build bit‐string & split
    for (size_t ci = 0; ci < *out_chunks_len; ci++) {
        state_t v = 0;
        for (int b = 0; b < size; b++) {
            size_t idx = ci * size + b;
            byte bit = 0;
            if (idx < total_bits) {
                size_t by = idx / 8;
                int    bb = 7 - (idx % 8);
                bit = (data[by] >> bb) & 1;
            }
            v = (v << 1) | bit;
        }
        chunks[ci] = v;
    }
    return chunks;
}

// **New**: unchunk exactly `bit_len` bits → `bit_len/8` bytes,
// ignoring any padded bits at the end.
byte* unchunk_bytes_trim(const state_t* chunks,
                         size_t         chunks_len,
                         int            size,
                         size_t         bit_len,
                         size_t*        out_data_len)
{
    *out_data_len = (bit_len + 7) / 8;
    byte* data = calloc(*out_data_len, 1);
    if (!data) exit(1);

    for (size_t ci = 0; ci < chunks_len; ci++) {
        state_t v = chunks[ci];
        for (int b = 0; b < size; b++) {
            size_t idx = ci * size + b;
            if (idx >= bit_len) break;  // stop at original bits
            size_t by = idx / 8;
            int    bb = 7 - (idx % 8);
            // recall chunk v stores MSB at bit (size-1)
            byte bit = (v >> (size - 1 - b)) & 1;
            data[by] |= bit << bb;
        }
    }
    return data;
}

static inline byte* unchunk_bytes(
    const state_t* chunks,
    size_t         chunks_len,
    int            size,
    size_t*        out_data_len
) {
    // rebuild all bits: chunks_len * size total bits
    return unchunk_bytes_trim(
        chunks,
        chunks_len,
        size,
        chunks_len * size,
        out_data_len
    );
}


// ─── Pack / unpack message ─────────────────────────────────────────────────

byte* pack_message(int    byte_length,
                   const byte* message,
                   size_t*       out_len)
{
    *out_len = _MESSAGE_HEADER_SIZE + byte_length;
    byte* buf = calloc(*out_len, 1);
    if (!buf) exit(1);

    char namebuf[16] = {0};
    snprintf(namebuf, sizeof(namebuf),
             "%s:msg", _ENCODING_VERSION);
    memcpy(buf, namebuf, 16);

    uint32_t bl = htonl((uint32_t)byte_length);
    memcpy(buf + 16, &bl, 4);

    memcpy(buf + _MESSAGE_HEADER_SIZE,
           message,
           byte_length);

    return buf;
}

void unpack_message(const byte* data,
                    size_t      data_len,
                    int*        out_byte_length,
                    byte**      out_message,
                    size_t*     out_payload_len)
{
    if (data_len < _MESSAGE_HEADER_SIZE) {
        fprintf(stderr,
                "message too short\n");
        exit(1);
    }
    char namebuf[17] = {0};
    memcpy(namebuf, data, 16);

    uint32_t bl_be;
    memcpy(&bl_be, data + 16, 4);
    *out_byte_length = ntohl(bl_be);

    char expected[32];
    snprintf(expected, sizeof(expected),
             "%s:msg", _ENCODING_VERSION);
    if (strcmp(namebuf, expected) != 0) {
        fprintf(stderr,
                "bad msg id '%s'\n",
                namebuf);
        exit(1);
    }

    *out_payload_len = data_len - _MESSAGE_HEADER_SIZE;
    *out_message = malloc(*out_payload_len);
    if (!*out_message) exit(1);

    memcpy(*out_message,
           data + _MESSAGE_HEADER_SIZE,
           *out_payload_len);
}

// ─── Pack / unpack public key ───────────────────────────────────────────────

byte* pack_public_key(int       ca_length,
                      int       repetitions,
                      RuleTable g,
                      size_t*   out_len)
{
    *out_len = _PUBLIC_HEADER_SIZE + g.bytes;
    byte* buf = calloc(*out_len,1);
    if (!buf) exit(1);

    char namebuf[16] = {0};
    snprintf(namebuf,sizeof(namebuf),
             "%s:pub",_ENCODING_VERSION);
    memcpy(buf, namebuf,16);

    uint16_t cl_be = htons((uint16_t)ca_length);
    uint16_t rp_be = htons((uint16_t)repetitions);
    memcpy(buf+16,&cl_be,2);
    memcpy(buf+18,&rp_be,2);

    memcpy(buf+_PUBLIC_HEADER_SIZE,
           g.tbl, g.bytes);

    return buf;
}

RuleTable unpack_public_key(const byte* data,
                            size_t      data_len,
                            int*        out_ca_length,
                            int*        out_repetitions)
{
    if (data_len < _PUBLIC_HEADER_SIZE) {
        fprintf(stderr,
                "pub key too short\n");
        exit(1);
    }
    char namebuf[17] = {0};
    memcpy(namebuf,data,16);

    char expected[32];
    snprintf(expected,sizeof(expected),
             "%s:pub",_ENCODING_VERSION);
    if (strcmp(namebuf,expected)!=0) {
        fprintf(stderr,
                "bad pub id '%s'\n",
                namebuf);
        exit(1);
    }

    uint16_t cl_be,rp_be;
    memcpy(&cl_be, data+16,2);
    memcpy(&rp_be, data+18,2);
    *out_ca_length   = ntohs(cl_be);
    *out_repetitions = ntohs(rp_be);

    size_t tbl_bytes = data_len - _PUBLIC_HEADER_SIZE;
    RuleTable R;
    R.bits  = 1u << *out_ca_length;
    R.bytes = tbl_bytes;
    R.tbl   = malloc(tbl_bytes);
    if (!R.tbl) exit(1);

    memcpy(R.tbl,
           data + _PUBLIC_HEADER_SIZE,
           tbl_bytes);

    return R;
}

// ─── Pack / unpack private key ──────────────────────────────────────────────

byte* pack_rules(const state_t* rules,
                 int            rule_depth,
                 int            neighborhood_size,
                 size_t*        out_len)
{
    int space = 1 << neighborhood_size;
    size_t chunk_size = (space + 7) / 8;
    *out_len = chunk_size * rule_depth;

    byte* buf = malloc(*out_len);
    if (!buf) exit(1);

    for (int i = 0; i < rule_depth; i++) {
        size_t rb;
        byte* t = int_to_bytes(rules[i], space, &rb);
        memcpy(buf + i*chunk_size, t, rb);
        free(t);
    }
    return buf;
}

state_t* unpack_rules(const byte* buf,
                      size_t      buf_len,
                      int         neighborhood_size,
                      int*        out_rule_depth)
{
    int space = 1 << neighborhood_size;
    size_t chunk_size = (space + 7) / 8;
    *out_rule_depth = buf_len / chunk_size;

    state_t* rules =
      malloc(*out_rule_depth * sizeof(state_t));
    if (!rules) exit(1);

    for (int i = 0; i < *out_rule_depth; i++) {
        state_t r = 0;
        for (size_t j = 0; j < chunk_size; j++) {
            r = (r << 8)
              | buf[i*chunk_size + j];
        }
        rules[i] = r;
    }
    return rules;
}

byte* pack_private_key(int           neighborhood_size,
                       int           ca_length,
                       int           repetitions,
                       int           rule_depth,
                       const state_t* rules,
                       size_t*        out_len)
{
    size_t rules_bytes_len;
    byte*  rules_bytes = pack_rules(
        rules, rule_depth,
        neighborhood_size,
        &rules_bytes_len);

    *out_len = _PRIVATE_HEADER_SIZE
             + rules_bytes_len;
    byte* buf = calloc(*out_len,1);
    if (!buf) exit(1);

    char namebuf[16] = {0};
    snprintf(namebuf,sizeof(namebuf),
             "%s:prv",_ENCODING_VERSION);
    memcpy(buf, namebuf, 16);

    uint16_t ns_be = htons((uint16_t)neighborhood_size);
    uint16_t cl_be = htons((uint16_t)ca_length);
    uint16_t rp_be = htons((uint16_t)repetitions);
    uint16_t rd_be = htons((uint16_t)rule_depth);

    memcpy(buf+16, &ns_be, 2);
    memcpy(buf+18, &cl_be, 2);
    memcpy(buf+20, &rp_be, 2);
    memcpy(buf+22, &rd_be, 2);

    memcpy(buf + _PRIVATE_HEADER_SIZE,
           rules_bytes,
           rules_bytes_len);

    free(rules_bytes);
    return buf;
}

void unpack_private_key(const byte* data,
                        size_t      data_len,
                        int*        out_neighborhood_size,
                        int*        out_ca_length,
                        int*        out_repetitions,
                        int*        out_rule_depth,
                        state_t**   out_rules)
{
    if (data_len < _PRIVATE_HEADER_SIZE) {
        fprintf(stderr,
                "prv key too short\n");
        exit(1);
    }
    char namebuf[17] = {0};
    memcpy(namebuf, data, 16);

    char expected[32];
    snprintf(expected,sizeof(expected),
             "%s:prv",_ENCODING_VERSION);
    if (strcmp(namebuf,expected)!=0) {
        fprintf(stderr,
                "bad prv id '%s'\n",
                namebuf);
        exit(1);
    }

    uint16_t ns_be,cl_be,rp_be,rd_be;
    memcpy(&ns_be,data+16,2);
    memcpy(&cl_be,data+18,2);
    memcpy(&rp_be,data+20,2);
    memcpy(&rd_be,data+22,2);

    *out_neighborhood_size = ntohs(ns_be);
    *out_ca_length         = ntohs(cl_be);
    *out_repetitions       = ntohs(rp_be);
    *out_rule_depth        = ntohs(rd_be);

    size_t rb_len = data_len - _PRIVATE_HEADER_SIZE;
    *out_rules = unpack_rules(
        data + _PRIVATE_HEADER_SIZE,
        rb_len,
        *out_neighborhood_size,
        out_rule_depth);
}

// ─── CA core routines ───────────────────────────────────────────────────────

state_t apply_once(state_t state,
                   RuleTable g,
                   int       L)
{
    state_t out = 0;
    for (int i = 0; i < L; i++) {
        state_t rot = rotate_right(state, i, L);
        byte b = (g.tbl[rot/8] >> (rot%8)) & 1;
        out |= ((state_t)b << i);
    }
    return out;
}

state_t* apply_rules(state_t        state,
                     const state_t* rules,
                     int            rule_depth,
                     int            L,
                     int            N)
{
    state_t* cur = malloc(sizeof(state_t));
    *cur = state;
    for (int i = 0; i < rule_depth; i++) {
        // invertible steps use full neighborhood
        state_t next = 0;
        for (int j = 0; j < L; j++) {
            state_t w = 0;
            for (int k = 0; k < N; k++) {
                int idx = (j + k) % L;
                w = (w << 1) | bit_at(*cur, idx);
            }
            byte bit = bit_at(rules[i], w);
            next |= ((state_t)bit << j);
        }
        *cur = next;
    }
    return cur;
}

state_t* make_inverse_map(const state_t* rules,
                          int            rule_depth,
                          int            L,
                          int            N)
{
    size_t space = 1u << L;
    state_t* inv = malloc(space * sizeof(state_t));
    bool*    used= calloc(space, sizeof(bool));

    for (size_t x = 0; x < space; x++) {
        state_t* yptr = apply_rules((state_t)x,
                                    rules,
                                    rule_depth,
                                    L, N);
        state_t y = *yptr;
        free(yptr);
        if (used[y]) {
            fprintf(stderr,"collision\n");
            exit(1);
        }
        used[y] = true;
        inv[y]  = (state_t)x;
    }
    free(used);
    return inv;
}

RuleTable make_public_key(const state_t* rules,
                          int            rule_depth,
                          int            L,
                          int            N)
{
    size_t space = 1u << L;
    RuleTable R;
    R.bits  = space;
    R.bytes = (space + 7)/8;
    R.tbl   = calloc(R.bytes, 1);
    if (!R.tbl) exit(1);

    for (size_t x = 0; x < space; x++) {
        state_t* yptr = apply_rules((state_t)x,
                                    rules,
                                    rule_depth,
                                    L, N);
        state_t y = *yptr;
        free(yptr);
        if (bit_at(y, 0)) {
            R.tbl[x/8] |= (1u << (x%8));
        }
    }
    return R;
}

// ─── High-level API ────────────────────────────────────────────────────────

void generate_key_pair(int     neighborhood_size,
                       int     ca_length,
                       int     repetitions,
                       int     rule_depth,
                       byte**  out_prv,
                       size_t* out_prv_len,
                       byte**  out_pub,
                       size_t* out_pub_len)
{
    if (neighborhood_size != _N) {
        fprintf(stderr,
                "only N=%d supported\n", _N);
        exit(1);
    }

    state_t* rules =
      malloc(rule_depth * sizeof(state_t));
    get_random_reversible_rules(
        ca_length, rule_depth, rules);

    *out_prv = pack_private_key(
        neighborhood_size,
        ca_length,
        repetitions,
        rule_depth,
        rules,
        out_prv_len);

    RuleTable g = make_public_key(
        rules,
        rule_depth,
        ca_length,
        neighborhood_size);

    *out_pub = pack_public_key(
        ca_length,
        repetitions,
        g,
        out_pub_len);

    free(g.tbl);
    free(rules);
}


byte* encrypt(
    const byte* public_key,
    size_t      public_key_len,
    const byte* message,
    size_t      message_len,
    size_t*     out_cipher_len
) {
    int ca_length, repetitions;
    RuleTable g = unpack_public_key(
        public_key,
        public_key_len,
        &ca_length,
        &repetitions
    );

    size_t chunks_len;
    state_t* chunks = chunk_bytes(
        message,
        message_len,
        ca_length,
        &chunks_len
    );

    for (size_t c = 0; c < chunks_len; c++) {
        for (int r = 0; r < repetitions; r++) {
            chunks[c] =
              apply_once(chunks[c],
                         g,
                         ca_length);
        }
    }
    free(g.tbl);

    size_t rec_len;
    byte* rec = unchunk_bytes(
        chunks,
        chunks_len,
        ca_length,
        &rec_len
    );
    free(chunks);

    // ─── NEW: write header with plaintext length, but copy ALL rec_len bytes ───
    size_t total = _MESSAGE_HEADER_SIZE + rec_len;
    byte* out = calloc(total, 1);
    if (!out) exit(1);

    // identifier
    char id[16] = {0};
    snprintf(id, 16, "%s:msg", _ENCODING_VERSION);
    memcpy(out, id, 16);

    // store plaintext length in header
    uint32_t bl = htonl((uint32_t)message_len);
    memcpy(out + 16, &bl, 4);
    // padding (bytes 20..30) are already zeroed by calloc

    // copy the full ciphertext
    memcpy(out + _MESSAGE_HEADER_SIZE, rec, rec_len);
    free(rec);

    *out_cipher_len = total;
    return out;
}


byte* decrypt(const byte* private_key,
              size_t private_key_len,
              const byte* cipher,
              size_t cipher_len,
              size_t* out_plain_len)
{
    int  neighborhood_size,
         ca_length,
         repetitions,
         rule_depth;
    state_t* rules;

    unpack_private_key(
        private_key,
        private_key_len,
        &neighborhood_size,
        &ca_length,
        &repetitions,
        &rule_depth,
        &rules);

    state_t* inverse = make_inverse_map(
        rules,
        rule_depth,
        ca_length,
        neighborhood_size);

    int    byte_length;
    byte*  encoded_payload;
    size_t payload_len;
    unpack_message(
        cipher,
        cipher_len,
        &byte_length,
        &encoded_payload,
        &payload_len);

    size_t chunks_len;
    state_t* chunks = chunk_bytes(
        encoded_payload,
        payload_len,
        ca_length,
        &chunks_len);
    free(encoded_payload);

    for (size_t c = 0; c < chunks_len; c++) {
        for (int r = 0; r < repetitions; r++) {
            chunks[c] = inverse[chunks[c]];
        }
    }
    free(inverse);
    free(rules);

    // rebuild exactly byte_length bytes:
    byte* out = unchunk_bytes_trim(
        chunks,
        chunks_len,
        ca_length,
        byte_length * 8,
        out_plain_len);
    free(chunks);

    return out;
}
