
// This program was generated by Chat GPT based on a Python script I wrote.
// I have not scrutinized it except to note that its outputs are 1-to-1 CAs on rings of length L.

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <time.h>
#include <inttypes.h>

#define MAX_L        32       // Absolute upper bound on L
#define SAFE_LIMIT   20       // Only fully test L ≤ 20 (2^20 ≈ 1 million states)
#define MAX_N        13       // Max odd N (so r = (N-1)/2 ≤ 6)
#define MAX_RULESIZE (1 << MAX_N)
#define RULE_WORDS   ((MAX_RULESIZE + 63) / 64)

/*──── Convert integer 'x' into its L-bit binary representation ────*/
static void int_to_bits(uint32_t x, int* bits, int L) {
    for (int i = 0; i < L; i++) {
        bits[i] = (x >> i) & 1;
    }
}

/*──── Convert an L-bit binary array 'bits' back into uint32_t ────*/
static uint32_t bits_to_int(int* bits, int L) {
    uint32_t out = 0;
    for (int i = 0; i < L; i++) {
        out |= (bits[i] << i);
    }
    return out;
}

/*──── Apply the CA rule of neighborhood on a ring of size L ────
   'config' is the current L-bit configuration, 'rule' is length 2^(2r+1), 'next' is output. */
static void apply_rule(const int* config, const int* rule, int* next, int N, int L) {
    for (int i = 0; i < L; i++) {
        int idx = 0;
        for (int offset = 0; offset < N; offset++) {
            int pos = (i + offset + L) % L;
            idx = (idx << 1) | config[pos];
        }
        next[i] = rule[idx];
    }
}

/*──── Check if 'rule' is globally reversible on a ring of size L ────
   Returns 1 if injective (i.e., no two distinct inputs map to same output), 0 otherwise. */
static int is_globally_reversible(const int* rule, int N, int L) {
    size_t space = (size_t)1 << L;
    uint8_t* seen = (uint8_t*)calloc(space, 1);
    if (!seen) {
        fprintf(stderr, "Error: calloc failed for seen[2^%d]\n", L);
        exit(1);
    }

    int config[MAX_L], next[MAX_L];
    for (uint32_t x = 0; x < (1U << L); x++) {
        int_to_bits(x, config, L);
        apply_rule(config, rule, next, N, L);
        uint32_t y = bits_to_int(next, L);
        if (seen[y]) {
            free(seen);
            return 0;
        }
        seen[y] = 1;
    }

    free(seen);
    return 1;
}

/*──── Verify that the forward-map followed by the built inverse recovers every input ────
   Returns 1 if for every x, inverse(forward(x)) == x; 0 otherwise. */
static int verify_inverse(const int* rule, int N, int L) {
    size_t space = (size_t)1 << L;
    int*      inverse = (int*)calloc(space, sizeof(int));
    uint8_t*  used    = (uint8_t*)calloc(space, 1);
    if (!inverse || !used) {
        fprintf(stderr, "Error: calloc failed in verify_inverse for L=%d\n", L);
        exit(1);
    }

    int config[MAX_L], next[MAX_L];
    /* Build forward→inverse map */
    for (uint32_t x = 0; x < (1U << L); x++) {
        int_to_bits(x, config, L);
        apply_rule(config, rule, next, N, L);
        uint32_t y = bits_to_int(next, L);
        if (used[y]) {
            /* collision → not invertible */
            free(inverse);
            free(used);
            return 0;
        }
        used[y]     = 1;
        inverse[y]  = x;
    }

    /* Check inverse(forward(x)) == x for all x */
    for (uint32_t x = 0; x < (1U << L); x++) {
        int_to_bits(x, config, L);
        apply_rule(config, rule, next, N, L);
        uint32_t y = bits_to_int(next, L);

        int recovered[MAX_L];
        int_to_bits(inverse[y], recovered, L);
        for (int i = 0; i < L; i++) {
            if (config[i] != recovered[i]) {
                free(inverse);
                free(used);
                return 0;
            }
        }
    }

    free(inverse);
    free(used);
    return 1;
}

/*──── Fill 'rule' array (length = rule_size) with random bits ────*/
static void random_rule(int* rule, int rule_size) {
    for (int i = 0; i < rule_size; i++) {
        rule[i] = rand() & 1;
    }
}

/*──── Pack the binary rule-table (length rule_size) into big-integer chunks ────
   'result_words' must be at least RULE_WORDS long.
   Each bit i in the large integer corresponds to rule[i]. */
static void rule_to_decimal(const int* rule, int rule_size, uint64_t* result_words) {
    memset(result_words, 0, RULE_WORDS * sizeof(uint64_t));
    for (int i = 0; i < rule_size; i++) {
        int word_index = i / 64;
        int bit_index  = i % 64;
        if (rule[i]) {
            result_words[word_index] |= (1ULL << bit_index);
        }
    }
}

/*──── Convert the big integer in 'words[0..word_count−1]' (base 2^64) to a decimal string ────*/
static void rule_to_decimal_str(const uint64_t* words, int word_count, char* outbuf, int bufsize) {
    uint64_t temp[RULE_WORDS];
    memcpy(temp, words, word_count * sizeof(uint64_t));

    char digits[8192];
    int  digit_len = 0;
    memset(digits, 0, sizeof(digits));

    /* Repeatedly divide by 10, collect remainders */
    while (1) {
        int all_zero = 1;
        uint64_t carry = 0;
        for (int i = word_count - 1; i >= 0; i--) {
            __uint128_t combined = ((__uint128_t)carry << 64) | temp[i];
            temp[i] = (uint64_t)(combined / 10);
            carry   = (uint64_t)(combined % 10);
            if (temp[i] != 0) {
                all_zero = 0;
            }
        }
        if (digit_len < (int)sizeof(digits) - 1) {
            digits[digit_len++] = (char)('0' + carry);
        } else {
            fprintf(stderr, "Error: decimal buffer overflow\n");
            exit(1);
        }
        if (all_zero) break;
    }

    /* Now reverse into outbuf */
    if (digit_len + 1 > bufsize) {
        fprintf(stderr, "Error: output buffer too small for decimal string\n");
        exit(1);
    }
    for (int i = 0; i < digit_len; i++) {
        outbuf[i] = digits[digit_len - 1 - i];
    }
    outbuf[digit_len] = '\0';
}

int main(int argc, char* argv[]) {
    if (argc != 3 && argc != 4) {
        fprintf(stderr,
            "Usage: %s <odd neighborhood size N ≤ %d> [min_L] <output_csv_path>\n",
            argv[0], MAX_N
        );
        return 1;
    }

    int N   = atoi(argv[1]);
    int min_L;
    const char* output_path;

    if (argc == 3) {
        /* No min_L provided; default to N */
        min_L      = N;
        output_path = argv[2];
    } else {
        /* argc == 4: parse min_L and output_path */
        min_L      = atoi(argv[2]);
        output_path = argv[3];
    }

    if (N <= 0 || N > MAX_N) {
        fprintf(stderr, "Error: N must be an integer in [1, %d].\n", MAX_N);
        return 1;
    }
    if (min_L < N || min_L > MAX_L) {
        fprintf(stderr, "Error: min_L must be in [%d, %d].\n", N, MAX_L);
        return 1;
    }

    int rule_size = 1 << N;  /* 2^N table-size */

    /* Open output CSV file in append mode */
    FILE* outfp = fopen(output_path, "a");
    if (!outfp) {
        fprintf(stderr, "Error: could not open output file '%s' for appending\n", output_path);
        return 1;
    }

    srand((unsigned)time(NULL));

    /* Allocate one rule-table of length = 2^N, plus space for big-integer */
    int*      rule       = (int*)malloc(sizeof(int) * rule_size);
    uint64_t* rule_words = (uint64_t*)malloc(sizeof(uint64_t) * RULE_WORDS);
    if (!rule || !rule_words) {
        fprintf(stderr, "Error: malloc failed for rule or rule_words\n");
        fclose(outfp);
        return 1;
    }

    /* Buffer for decimal representation */
    char decimal_str[8192];

    /* For each base_L from min_L..MAX_L, attempt up to 100000000 random rules */
    for (int base_L = min_L; base_L <= MAX_L; base_L++) {
        printf("\n🔍 Searching for any reversible CA-rule (N=%d, L=%d)...\n", N, base_L);
        int found_any_at_base = 0;

        for (long long int attempt = 0; attempt < (1LL << 32); attempt++) {
//            random_rule(rule, rule_size);
            for (int i = 0; i < rule_size; i++) {
                rule[i] = (attempt >> i) & 1;
            }

            if (base_L > SAFE_LIMIT) {
                /* Skip full test if L exceeds safe limit */
                if (attempt == 0) {
                    printf(
                        "⚠ Skipped full reversibility test at L=%d (L > %d yields 2^L > 1e6 states).\n",
                        base_L, SAFE_LIMIT
                    );
                }
                break;
            }

            if (is_globally_reversible(rule, N, base_L) &&
                verify_inverse(rule, N, base_L))
            {
                found_any_at_base++;
                rule_to_decimal(rule, rule_size, rule_words);
                rule_to_decimal_str(rule_words, RULE_WORDS, decimal_str, sizeof(decimal_str));

                /* Now check all L2 ≥ min_L up to SAFE_LIMIT for this same rule */
                printf("✅ [%d] Reversible rule found (attempt %lld)\n", found_any_at_base, attempt);
                printf("   Rule number (decimal) = %s\n", decimal_str);

                printf("   Checking reversibility for L2 ≥ %d:\n", min_L);
                for (int L2 = N; L2 <= MAX_L; L2++) {
                    if (L2 > SAFE_LIMIT) {
                        break;
                    }
                    int ok_rev = is_globally_reversible(rule, N, L2);
                    int ok_inv = ok_rev ? verify_inverse(rule, N, L2) : 0;
                    if (ok_rev && ok_inv) {
                        /* Append one CSV line per (rule_number, L2) */
                        fprintf(outfp, "%s,%d\n", decimal_str, L2);
                        fflush(outfp);
                        printf("     • Reversible at L2=%d → appended: %s,%d\n", L2, decimal_str, L2);
                    }
                }
            }
        }

        if (!found_any_at_base && base_L <= SAFE_LIMIT) {
            printf("❌ No reversible rule found at L=%d after 100000000 attempts.\n", base_L);
        }
        else if (!found_any_at_base && base_L > SAFE_LIMIT) {
            printf("⚠ Skipped searching at L=%d (too large to test fully).\n", base_L);
            break;
        }
    }

    free(rule);
    free(rule_words);
    fclose(outfp);
    return 0;
}
